name: Test CICE5 build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    uses: access-nri/workflows/.github/workflows/build-package.yml@main
    with:
      container-registry: ghcr.io
      container-name: access-nri/build-cice5-intel2021.1.2
      package-name: cice5
      compiler-name: intel
      compiler-version: 2021.1.2
      spack-packages-version: enable_branch_use_for_cice5
    permissions:
      packages: read
